### ISSUE TITLE
any smarter?

### ISSUE THREAD

**Issue by OpenMachinesAI** [kyutai-labs/moshi#103]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

Other / All

### Question

is it posible to make this model smarter using LLAMA or just by scaling?

If yes can someone help with this?

**Comment by OpenMachinesAI** [comment]
idk i think its all one multimodal model?

**Comment by LaurentMazare** [comment]
Indeed it's a all in one model so switching the text backbone requires some significant retraining.
