### ISSUE TITLE
chinese will be supported ?

### ISSUE THREAD

**Issue by ucas010** [kyutai-labs/moshi#104]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

Other / All

### Question

could i speak chinese with the Moshi ?

**Comment by Alaodeha1453** [comment]
عربي

في الاثنين، ٢٣ أيلول ٢٠٢٤, ٦:١٣ ص Lychee X ***@***.***> كتب:

**Comment by baby1000001000** [comment]
the same question

expectation...

**Comment by LaurentMazare** [comment]
I don't think we would have the dataset to train moshi on chinese. Our goal is to release some finetuning scripts at some point and we hope for the community to train moshi variants for different languages and use cases based on this.
