### ISSUE TITLE
Has there been an assessment of ASR function?

### ISSUE THREAD

**Issue by zly-idleness** [kyutai-labs/moshi#105]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The PyTorch implementation

### Question

About asr capability, can it be used directly as an asr model? Have you performed any evaluations on any datasets?

**Comment by zly-idleness** [comment]
So , the trained ASR model is not released right ? the released moshi model can not directly use to perform ASR tasks by just changing the delays?

I have change delays like this , but the output seems not doing transcription:
 ```py
 # "delays": [0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
    "delays": [4, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2],
   ```

**Comment by LaurentMazare** [comment]
The released model would not do ASR indeed, you need to retrain it after changing the delays. We aim at releasing the training codebase at some point but don't have an estimated timeline for this yet.

**Comment by zly-idleness** [comment]
> The released model would not do ASR indeed, you need to retrain it after changing the delays. We aim at releasing the training codebase at some point but don't have an estimated timeline for this yet.

Thank You ! Looking forward to the training codebase release.
