### ISSUE TITLE
How to run moshi_mlx.local_web on a Mac so that others can use the demo on other machines?

### ISSUE THREAD

**Issue by kebibulaient24** [kyutai-labs/moshi#106]
I run python -m moshi_mlx.local_web -q 4 --host 172.18.150.107 --port 8080 on a Mac and can see index.html, but when I click Connect, the following error occurs:
<img width="1453" alt="image" src="https://github.com/user-attachments/assets/355b2bde-1fb1-44f0-a09d-72645e7a48f2">
When --host=localhost, it can be used normally. How do I run moshi_mlx.local_web on a Mac so that others can use the demo on other machines?

**Comment by kebibulaient24** [comment]
when --host=localhost:
![image](https://github.com/user-attachments/assets/d22a31dd-7f0e-4572-8c25-858c4350d7be)
when --host=172.18.150.107:
![image](https://github.com/user-attachments/assets/d22a31dd-7f0e-4572-8c25-858c4350d7be)

**Comment by LaurentMazare** [comment]
If the other machines can log onto the machine where the server is running via ssh, you can tunnel port 8998 using the `-L` flag and then use `http://localhost:8998` on the client machines.

**Comment by LaurentMazare** [comment]
Closing now as hopefully the https version or the port tunneling help for this use case.
