### ISSUE TITLE
Step of Depth Transformer

### ISSUE THREAD

**Issue by MeNicefellow** [kyutai-labs/moshi#112]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The PyTorch implementation

### Question

I find at line 314 of https://github.com/kyutai-labs/moshi/blob/main/moshi/moshi/models/lm.py
depformer_input = depformer_input + last_token_input while previously depformer_input = transformer_out

This means the transformer_out is added to the last_token_input. Then there is always only one token for the Depth Transformer. Shouldn't there be k tokens/vectors when it is to generate the k+1 th token?

**Comment by TianwenWei** [comment]
The KV cache is automatically handled in class `StreamingMultiheadAttention(StreamingModule[_MHAState])`, which is called indirectly within the forward method of the transformer.

**Comment by LaurentMazare** [comment]
Indeed the KV cache is passed along the different stages of the depth transformer so generating the k+1 tokens it can use the context from all the previous k tokens. The implementation is a bit convoluted on the pytorch side, so you can also look at the [mlx implementation](https://github.com/kyutai-labs/moshi/blob/35a9f4308e5225b701e18c31dceed6750045c885/moshi_mlx/moshi_mlx/models/lm.py#L91-L99) which I find a bit easier to follow.
