### ISSUE TITLE
Error: DriverError(CUDA_ERROR_UNSUPPORTED_PTX_VERSION, "the provided PTX was compiled with an unsupported toolchain.") when loading cast_f32_bf16

### ISSUE THREAD

**Issue by Roland-Du** [kyutai-labs/moshi#114]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The Rust implementation

### Question

I am running rust mode to start, boot on CUda failed, the following error message, with the environment version:

cargo run --features cuda --bin moshi-backend -r -- --config moshi-backend/config.json standalone

Finished `release` profile [optimized + debuginfo] target(s) in 0.30s
     Running `target/release/moshi-backend --config moshi-backend/config.json standalone`
2024-09-25T08:24:44.101130Z  INFO moshi_backend: build_info=BuildInfo { build_timestamp: "2024-09-25T07:45:58.387823393Z", build_date: "2024-09-25", git_branch: "main", git_timestamp: "2024-09-24T10:21:18.000000000+02:00", git_date: "2024-09-24", git_hash: "5d94128878678bb6e5a9471aed8c78f4d96eb473", git_describe: "5d94128", rustc_host_triple: "x86_64-unknown-linux-gnu", rustc_version: "1.81.0", cargo_target_triple: "x86_64-unknown-linux-gnu" }
2024-09-25T08:24:44.101151Z  INFO moshi_backend: starting process with pid 639339
2024-09-25T08:24:44.101177Z  INFO hf_hub: Token file not found "/root/.cache/huggingface/token"    
2024-09-25T08:24:44.118232Z  INFO hf_hub: Token file not found "/root/.cache/huggingface/token"    
Error: DriverError(CUDA_ERROR_UNSUPPORTED_PTX_VERSION, "the provided PTX was compiled with an unsupported toolchain.") when loading cast_f32_bf16

other Version :
(moshi) [root@VM-0-6-tencentos rust]# rustc -V
rustc 1.81.0 (eeb90cda1 2024-09-04)
(moshi) [root@VM-0-6-tencentos rust]# cargo -V
cargo 1.81.0 (2dbb1af80 2024-08-20)
(moshi) [root@VM-0-6-tencentos rust]# nvidia-smi 
Wed Sep 25 16:27:07 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       On  | 00000000:00:08.0 Off |                    0 |
| N/A   32C    P8              11W /  70W |      2MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
(moshi) [root@VM-0-6-tencentos rust]# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:19:38_PST_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0
(moshi) [root@VM-0-6-tencentos rust]# python -V
Python 3.12.5

**Comment by LaurentMazare** [comment]
Looks like your nvcc version is for cuda 12.4 but according to the "Api Support" of your [driver release notes](https://docs.nvidia.com/datacenter/tesla/tesla-release-notes-535-161-07/index.html) the drivers only support up to cuda 12.2. Maybe try updating the drivers? (though it's hard to be sure that this is the culprit here)

**Comment by Roland-Du** [comment]
Okay, thanks. I'll try to update the driver

> Looks like your nvcc version is for cuda 12.4 but according to the "Api Support" of your [driver release notes](https://docs.nvidia.com/datacenter/tesla/tesla-release-notes-535-161-07/index.html) the drivers only support up to cuda 12.2. Maybe try updating the drivers? (though it's hard to be sure that this is the culprit here)看起来你的nvcc版本是针对cuda 12.4的，但根据驱动程序发布说明的“Api支持”，驱动程序只支持cuda 12.2。也许可以尝试更新驱动程序?(虽然很难确定这就是罪魁祸首)

**Comment by LaurentMazare** [comment]
Closing for now, feel free to reopen if you run into further issues.
