### ISSUE TITLE
Request to Open-Source Helium Base Model

### ISSUE THREAD

**Issue by ArmeriaWang** [kyutai-labs/moshi#117]
Hi moshi team,

Thank you for the great work on moshi! Would it be possible to open-source the Helium base model? As a single-language large model, it has significant potential for fine-tuning on speech tasks and would be a valuable resource for both the speech and NLP communities.

Thanks for considering!

**Comment by adefossez** [comment]
We do not have plans to release the text model Helium at this time. There is already a large number of open source text models that are likely to be good fits. Or maybe you mean the base Moshi model ? Similarly, we have no plan to release it at the moment.

**Comment by Ronnie-Leon76** [comment]
Is it possible to swap Helium, 7B-parameter text LLM with Llama 3?

**Comment by LaurentMazare** [comment]
The approach we use for moshi consist in training the 7b model on speech data with an initialization based on text data, so the cost of retraining on another LLM is significant. Also the llama-3 license is not very permissive so if we were to do this we would have to call the model llama-moshi so we don't have some immediate plans for doing this.

**Comment by XhqGlorry11** [comment]
@LaurentMazare Hi, can you share the tokenizer of Helium. I'd like to do some data verification with moshi, which needs Helium tokenizer to encode text into monologues. Thanks.

**Comment by LaurentMazare** [comment]
The text tokenizer is actually already available, e.g. `tokenizer_spm_32k_3.model` [here](https://huggingface.co/kyutai/moshiko-candle-bf16/tree/main).
