### ISSUE TITLE
Number of quantizers

### ISSUE THREAD

**Issue by mithileshvaidya** [kyutai-labs/moshi#122]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The paper

### Question

Why does the default configuration have 32 quantizers, instead of 8, as mentioned in the paper?
More specifically, I used the default HuggingFace implementation. On running `encoder_outputs = model.encode(inputs["input_values"])`,  I get a tensor of shape [B, 32, T] instead of [B, 8, T]. If I reduce the num_quantizers to 8, the reconstruction quality is quite poor.
Am I missing something?

**Comment by erogol** [comment]
yeah I don't think the released mimi is the one used at moshi training.

**Comment by LaurentMazare** [comment]
The released mimi has indeed 32 rvq levels, you can see them in [model.safetensors](https://huggingface.co/kyutai/mimi/tree/main?show_file_info=model.safetensors), and it provides the highest quality. However in moshi we only use the first 8 levels so as to improve latency, generally 8 levels is enough for good sounding voices, 16 levels has some marginal but audible quality improvement, from 16 to 32 I wouldn't hear much of a difference myself but we still wanted to provide the best possible codec so we included all these.

**Comment by erogol** [comment]
Thanks for clarifying. I've tried zeroing the 8: and reconstructing the audio but it sounds bad. Any feedback on that?

**Comment by LaurentMazare** [comment]
Not sure what you mean by "zeroing the 8", but rather than passing 0 tokens for the codebooks that you don't want to use you should instead not pass the values at all so that no value is actually added to the latents. I'm not sure though if the HuggingFace version supports this, tagging @ylacombe who wrothe the HF port.

**Comment by erogol** [comment]
sorry I meant ```codes[:, 8:] = 0```

and yes I was using the HF version but yes I guess I can try the native implementation

**Comment by ylacombe** [comment]
Hey, you can simply specify [`num_quantizers`](https://huggingface.co/docs/transformers/model_doc/mimi#transformers.MimiModel.encode.num_quantizers) in the `model.encode` method!

```py
audio_codes = model.encode(audio, num_quantizers=8)
audio_values = model.decode(audio_codes)[0]
```

**Comment by ylacombe** [comment]
No need to set the codebooks to zero, since Mimi doesn't have a PAD token

**Comment by mithileshvaidya** [comment]
Thank you for the clarification!
