### ISSUE TITLE
Moshi Rust server doesn't start - model.safetensors has been renamed

### ISSUE THREAD

**Issue by pcbua** [kyutai-labs/moshi#129]
### Backend impacted

The Rust implementation

### Operating system

Linux

### Hardware

GPU with CUDA

### Description

During starting Rust server:
   `cargo run --features cuda --bin moshi-backend -r -- --config moshi-backend/config.json standalone`
There is an error:
  `Error: Failed to download '/home/ja/tmp/moshiko_rs_301e30bf@120.safetensors' file`

It looks like someone renamed `moshiko_rs_301e30bf@120.safetensors` to `model.safetensors`, and forgot update related scripts.
Can you fix it? Or provide instruction what to change?

### Extra information

I hope description is enough.
I encourage You to reproduce - following the official instruction in README - just pretend you are doing it first time.

### Environment

It doesn't really matter, but I have:
- OS: Ubuntu 22.04.1
- Python version: 3.12.2
- Torch version: 2.4.1
- CUDA version: 12.4
- GPU: RTX 3090

**Comment by LaurentMazare** [comment]
Thanks for reporting this, indeed the files were renamed but the configs weren't updated, should be fixed in #130
