### ISSUE TITLE
Modeling "other" audio stream

### ISSUE THREAD

**Issue by ArEsKay3** [kyutai-labs/moshi#131]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The PyTorch implementation

### Question

Hi!
I'm interested in exploring/playing with Moshi's ability to model duplex audio.
IIUC, the model released only includes the weights to decode the Moshi audio stream. (dep_q == 8)
Is there a place to get the right weights to generate the other audio stream tokens (specifically the projection and decoder layers for the depformer, dep_q == 16)?
Thanks!

**Comment by LaurentMazare** [comment]
We haven't released a model with the 16 depformer layers at this point. This may be the case when we release the fine-tuning code though we don't have an exact timeline for this yet.
