### ISSUE TITLE
questions for M1 Mac

### ISSUE THREAD

**Issue by scalar27** [kyutai-labs/moshi#139]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The MLX implementation

### Question

I have an M1 Macbook pro with 64Gb and the mlx version seems to work properly.  Thank you very much for this exciting project.  I just have a couple of lingering questions:
* can I use the pytorch version and its larger model, or is that cuda only?
* can I use moshiko/moshika with the web interface?
* I'm not sure what Rust/Candle are supposed to do.  Is this relevant for the M1 Mac?

**Comment by LaurentMazare** [comment]
- The models for the pytorch and mlx versions are exactly the same, so there isn't much interest in running the pytorch version on a mac.
- You can use the web UI via `python -m moshi_mlx.local_web` (see the readme).
- Rust/Candle provides an alternative implementation which is useful for larger deployments of the model, probably not much relevant for running locally on a m1 mac.

**Comment by scalar27** [comment]
Thanks.  For the second one, I'd like to use the web UI with the moshika voice.  Is that possible?

**Comment by LaurentMazare** [comment]
Yes there are examples of how to do this in the readme.
