### ISSUE TITLE
Is an Intel build on the roadmap?

### ISSUE THREAD

**Issue by rubbercable** [kyutai-labs/moshi#140]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The MLX implementation

### Question

Will there ever be a release for this for an IntelChipset?
If so; where will this exist on a roadmap?

**Comment by LaurentMazare** [comment]
This sounds more like a MLX question: our MLX implementation doesn't have anything specific to apple silicon so if MLX start supporting computer with intel chipsets (and the associated gpus) at some point, moshi should benefit from it.
