### ISSUE TITLE
Unable to Install Triton for Moshi AI on Windows

### ISSUE THREAD

**Issue by tropicalstream** [kyutai-labs/moshi#142]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The PyTorch implementation

### Question

I have been attempting to install Moshi AI on my Windows 4090 machine, but I’m running into issues with the Triton installation, which prevents the model from running successfully. Despite trying multiple methods, including the recommended steps from both the official Triton and Moshi documentation, I haven’t been able to resolve the error. Here are the details of my setup and the steps I've tried so far:

System Information:

OS: Windows 10
Python version: 3.10
CUDA version: 11.8
PyTorch version: 2.4.1 (installed via pip)
Triton version: 2.0.0 (attempted installation from GitHub)
Steps I’ve Tried:

Cloning the Triton GitHub repository and installing it via pip install -e .
Attempted multiple versions of Triton installation (via git, pip, and even manually editing the pyproject.toml).
Re-installed the PyTorch packages using the nightly build to ensure compatibility with CUDA 11.8.
Suppressing errors in PyTorch’s dynamo by setting torch._dynamo.config.suppress_errors = True.
Error Encountered:
When I try to run the Moshi server, I consistently get the following error:

arduino
Copy code
RuntimeError: Cannot find a working triton installation. More information on installing Triton can be found at https://github.com/openai/triton

**Comment by LaurentMazare** [comment]
This seems more like a triton/pytorch issue so not sure that we could be of any help here.

**Comment by LaurentMazare** [comment]
Closing as not much activity and probably unrelated to moshi itself.
