### ISSUE TITLE
Does the Mimi Codec's Weight Change During Moshi Training?

### ISSUE THREAD

**Issue by qa6300525** [kyutai-labs/moshi#143]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The paper

### Question

What is the training process like?
My current understanding of the training process is: first, the Mimi codec and the Helium text language model are trained separately, and then Moshi is trained.
I would like to know whether Mimi's weights are updated during the training of Moshi?

Thank you for the great work

**Comment by LaurentMazare** [comment]
Mimi weights are frozen during the training of the moshi part.
