### ISSUE TITLE
Mimi Model Quantizer Configuration

### ISSUE THREAD

**Issue by WWWWxp** [kyutai-labs/moshi#144]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The paper

### Question

Hello, I would like to ask a question. In the paper, we see that the Mimi model has Q=8 quantizers, but in the open-source Mimi model on Hugging Face, the default setting is num_quantizers=32. Are the configurations of the open-source Mimi and the one in the paper different?

**Comment by hdmjdp** [comment]
same question

**Comment by LaurentMazare** [comment]
We have different versions of mimi, typically with 8, 16, and 32 quantizers. The open-source release has the full 32 quantizers though when using moshi we only generate the first 8 levels so have a slightly degraded audio quality.
