### ISSUE TITLE
Is Depth Transformer applied over K=4 steps in inference code? 

### ISSUE THREAD

**Issue by itsliupeng** [kyutai-labs/moshi#166]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The PyTorch implementation

### Question

Could you clarify the inference code? I noticed that the Depth Transformer is applied only over 1 step, not K steps.

On the other hand, if the Depth Transformer were used over K=4 steps, summing the 4 embeddings during input would introduce latency for the user stream's input.

<img width="916" alt="image" src="https://github.com/user-attachments/assets/872b38f3-38c1-4798-b0b6-059811fc28c4">

**Comment by LaurentMazare** [comment]
The depth-transformer is only applied over one temporal step, hence the "temporal context" being used by all the depth-transformer stages in the figures you quoted. However the depth transpformer has multiple steps, K is set to 4 in the figure but in the inference code it's usually K=8 or K=16.
In the inference code, you can see this loop over the K depth-transformer steps in the loop [here](https://github.com/kyutai-labs/moshi/blob/eee03a63e9f901710f0673e7b00a4c052594c88d/moshi/moshi/models/lm.py#L471), it's important to notice that this loop and the `depformer_step` function are called once per temporal step so there is no added latency.

**Comment by itsliupeng** [comment]
> The depth-transformer is only applied over one temporal step, hence the "temporal context" being used by all the depth-transformer stages in the figures you quoted. However the depth transpformer has multiple steps, K is set to 4 in the figure but in the inference code it's usually K=8 or K=16. In the inference code, you can see this loop over the K depth-transformer steps in the loop [here](https://github.com/kyutai-labs/moshi/blob/eee03a63e9f901710f0673e7b00a4c052594c88d/moshi/moshi/models/lm.py#L471), it's important to notice that this loop and the `depformer_step` function are called once per temporal step so there is no added latency.

Are you saying that K = lm_model.dep_q,  which corresponds to the number of notebooks for the Moshi audio stream? I'm curious, is Zs also at 12.5Hz? In other words, do the corresponding text tokens also operate at 12.5Hz?

**Comment by LaurentMazare** [comment]
Yes K in the paper is `dep_q` in the pytorch code, which could be 8/16/32 depending on the model. The temporal transformer runs at 12.5Hz and emit the temporal context as well as a text token at this frequency. More details on how the text tokens are lined up with the actual text through text tokens are given in the paper.

**Comment by jlian2** [comment]
Thanks. IN your current released model, it turns out the model supports K=8, Any plans to release the model also supports K=16 to enable user stream prediction?
