### ISSUE TITLE
Semantic token inference for user stream

### ISSUE THREAD

**Issue by jtkim-kaist** [kyutai-labs/moshi#175]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The PyTorch implementation

### Question

(My question is about the behavior of depformer in the training phase) I found that the semantic token inference for **moshi** stream is based on depformer's text emb and transformer_out 

```python
        depformer_input = transformer_out
        if self.depformer_multi_linear:
            depformer_input = self.depformer_in[depformer_cb_index](depformer_input)  # depformer_in: cb_index 별로 trasnforme_out encoding
        else:
            depformer_input = self.depformer_in[0](depformer_input)
        if depformer_cb_index == 0:
            last_token_input = self.depformer_text_emb(sequence[:, 0])
        else:
            last_token_input = self.depformer_emb[depformer_cb_index - 1](
                sequence[:, 0]
            )
        depformer_input = depformer_input + last_token_input
        assert depformer_input.shape[1] == 1
        # depformer_input is [B, 1, depformer_dim].
        # The streaming state of the depformer ensures that the proper layer is run.
        dep_output = self.depformer(depformer_input)
``` 

However, for the user stream, there is **no text_emb** so how can do the inference for semantic token? At the first time I see the paper, the author wrote that they simply concat the text, moshi and user stream along the codebook dimension so I guess the semantice token inference for user stream can be done with last acoustic token for moshi stream; however, in the code, there is no depformer_in for the last acoustic token with the comment "# Only using up to dep_q - 1 because the last codebook is never an input to Depformer." ; so my guess is incorrect.

Could you let me know how the user stream's semantic token inference can be done? did you insert some zero values between user and moshi stream? or use user's text stream only for the training phase?

**Comment by LaurentMazare** [comment]
I'm not sure to understand your guess correctly but I think it's correct.
- The main transformer produces `transformer_out` and the text token.
- The depformer produces 16 audio tokens, 8 for moshi, 8 for the user (in that order).
- The first depformer layer uses the text token.
- Each subsequent depformer layer uses the token from the previous layer.
With this in mind, you can see that the semantic token for moshi is based on `transformer_out` and the text token, and the semantic token for the user is based on `transformer_out` and the last acoustic token for moshi. However note that the depformer layers use a common kv cache so the layer predicting the semantic token for the user can attend to information about the text token.
Finally the comment saying that "Only using up to dep_q - 1 because the last codebook is never an input to Depformer.", this means that the token generated by the last depformer layer (which is the last acoustic token for the user) is not used by any depformer layer as there is no subsequent layer.

**Comment by jtkim-kaist** [comment]
Thank you for the fast response! I attached the further detail of my question depending on your comments.
----------------------------------------------------------------------------------------------------
There is a contradiction between your comments (also this is what I pointed out):

_comment A_
"the semantic token for the user is based on transformer_out and the **last acoustic token for moshi.**"

and

_comment B_
"this means that the token generated by **the last depformer layer** (which is the last acoustic token for the user) is not used by any depformer layer as there is no subsequent layer."

Based on _comment A_, the last acoustic token for moshi is necessary for the user's semantic token inference, However, due to the absence of the last depformer layer, we cannot get the **last acoustic token embedding for moshi**, 
```python
self.depformer_text_emb
ScaledEmbedding(32001, 1024)

self.depformer_emb
ModuleList(
  (0-6): 7 x ScaledEmbedding(2049, 1024)
)
``` 
In the above code block, we can check that the total number of embedding layer is 7 (1 text, 7 acoustic); thus we only can get the 7th acoustic embedding, while the 8th acoustic embedding for moshi is necessary for the user's semantic token inference.

Therefore, the question is: how can I get the 8th acoustic embedding for moshi for the user's semantic token inference.

Also, cache related stuff may be out of scope in our discussion because caching technique may be used only for the inference phase, not for the training phase.

**Comment by LaurentMazare** [comment]
When training, the depformer uses 16 layers. However when running inference we only need to produce the tokens for Moshi so only run the first 8 layers, hence the weights that we released only use 8 layers and never generate the user audio tokens.
What I meant by KV cache shared by the layers is the causal attention mechanism that is used by the depformer and apply both to training and inference (but indeed the term KV cache is not very appropriate here).

**Comment by jtkim-kaist** [comment]
I perfectly understand the points from "the depformer uses 16 layers" Thank you for your great contributions and fast & kind answer!

**Comment by kalvinchang** [comment]
@LaurentMazare 

My team and I are trying to evaluate our post-trained Moshi model on the task of Generated Dialogues / conversation continuation (Section 5.6). This requires predicting the user stream, which in turn requires predicting 8 user codes at inference time. We are also trying to evaluate our post-trained Moshi on StoryCloze. We would like to follow the paper's evaluation and use the user stream:
> Similarly, when evaluating a multi-stream model after instruction tuning, we only score the tokens from the user stream as it does not include text tokens.
However, this is not possible with the released model.

Would it be possible the share the 8 user depformer layers? Thanks!

Same issue as https://github.com/kyutai-labs/moshi/issues/188
