### ISSUE TITLE
Any Plans to release fine-tuning code?

### ISSUE THREAD

**Issue by AshwinSankar17** [kyutai-labs/moshi#50]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The PyTorch implementation

### Question
Congratulations and thank you for the open source contribution.
Is there any plans to release a fine-tuning code/guide? I would love to see extended this to other languages.

**Comment by adefossez** [comment]
We don't have a timeline yet, but we will release training code in the coming months.

**Comment by hopto-dot** [comment]
@adefossez Will this mean you can train it to have any voice? Or make it compatible with any language?

**Comment by adefossez** [comment]
I don't really have an answer to your question at that point!
I will be closing this issue at this point to clean things up, I've started a new FAQ section to try to summarize things: 
https://github.com/kyutai-labs/moshi/blob/main/FAQ.md
