### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by fakerybakery** [kyutai-labs/moshi#52]
Hi,
Thanks for releasing Moshi! Are there any plans to release the dataset used to train your speech to speech model?
Thanks!

**Comment by akshatvishu** [comment]
Dataset will not be made public.

ref: <https://github.com/kyutai-labs/moshi/blob/main/FAQ.md>

**Comment by adefossez** [comment]
thanks for referencing the FAQ, I just added it to avoid getting too many duplicate questions!
