### ISSUE TITLE
Training Code

### ISSUE THREAD

**Issue by fakerybakery** [kyutai-labs/moshi#53]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

Other / All

### Question

Hi,
Thanks for releasing Moshi! Are there any plans to release the pre training code?
Thanks!

**Comment by akshatvishu** [comment]
The [FAQ](https://github.com/kyutai-labs/moshi/blob/main/FAQ.md) has been updated to address this. They plan to release it in the near future (no specific date provided).
