### ISSUE TITLE
How do I change the personality or  system prompt

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [kyutai-labs/moshi#57]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The PyTorch implementation

### Question

Hello, you are all excited for this to be launched funny I was talking about you all.

I want to be able to change my personality I got Gradio going in lighting studio with PyTorch python build.

But I do not see where I change my personality if that is a thing or if it just learns over time.

Any advice is much appreciated thank you.

**Comment by akshatvishu** [comment]
\https://github.com/kyutai-labs/moshi/blob/main/FAQ.md#can-i-change-moshis-voice--personality
