### ISSUE TITLE
Cannot install moshi-mlx

### ISSUE THREAD

**Issue by boji123** [kyutai-labs/moshi#63]
### Backend impacted

The PyTorch implementation

### Operating system

Linux

### Hardware

CPU

### Description

`INFO: pip is looking at multiple versions of moshi-mlx to determine which version is compatible with other requirements. This could take a while.
Collecting moshi_mlx
  Using cached http://mirrors.tencentyun.com/pypi/packages/95/bc/f1952075f7eb11155cd818ac6a42a5dfd31f3fe7ae94856eb405bae18aa1/moshi_mlx-0.0.0-py3-none-any.whl (1.4 kB)
ERROR: Cannot install moshi-mlx==0.0.0 and moshi-mlx==0.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    moshi-mlx 0.1.0 depends on mlx<0.18 and >=0.17.2
    moshi-mlx 0.0.0 depends on mlx<0.18 and >=0.17.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
`

### Extra information

`conda create -n moshi python=3.10
conda activate moshi

export RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup
export RUSTUP_DIST_SERVER=https://mirrors.ustc.edu.cn/rust-static
curl https://sh.rustup.rs -sSf | sh # install Cargo, the Rust package manager
. "$HOME/.cargo/env" # source Cargo

pip install moshi      # moshi PyTorch, from PyPI
pip install moshi_mlx  # moshi MLX, from PyPI`

blocked at pip install moshi_mlx

### Environment

Fill in the following information on your system.
- Operating system version:

If the backend impacted is PyTorch:
- Python version:
- PyTorch version:
- CUDA version (run `python -c 'import torch;  print(torch.version.cuda)'`):
- GPU model and memory:
  
If the backend is MLX:
- Mac model:

**Comment by do-me** [comment]
You cannot install the mlx version (designed for Apple Silicon) on Linux. Try with the CUDA version if you have a GPU. CPU-only doesn't work yet afaik.

**Comment by adefossez** [comment]
closing as @do-me  summarized the situation :)

**Comment by do-me** [comment]
Sure that should work with the normal cuda version. Just make sure the install the right backend (not -mlx).
