### ISSUE TITLE
Cannot install moshi-mlx on M3 Max

### ISSUE THREAD

**Issue by Chuhao994** [kyutai-labs/moshi#66]
### Backend impacted

The MLX implementation

### Operating system

Mac OS X

### Hardware

Metal with MLX

### Description

Hello,

I'm encountering some issues while attempting to install Moshi MLX and would greatly appreciate your advice.

Initially, I executed the following command in the terminal:

pip install moshi_mlx

However, the installation process failed, indicating that I needed to install the Rust toolchain. Following the instructions provided, I then ran this command to install Rust:

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh  
Unfortunately, during the Rust installation process, I encountered the error as screenshot.

Given these circumstances, could you please provide guidance on how to resolve this issue? My ultimate goal is to successfully install Moshi MLX along with all its required dependencies.

Thx
<img width="568" alt="2024-09-19 16 59 31" src="https://github.com/user-attachments/assets/56a636c7-a749-485c-97f4-f65860867d27">

### Extra information

<img width="568" alt="2024-09-19 16 59 31" src="https://github.com/user-attachments/assets/4f93c400-87ce-48ac-87fa-b8e9c9235b63">

### Environment

Fill in the following information on your system.
- Operating system version: MacOS 14.6.1

If the backend impacted is PyTorch:
- Python version: 3.11
- PyTorch version: yet to install
- CUDA version (run `python -c 'import torch;  print(torch.version.cuda)'`):
- GPU model and memory:
  
If the backend is MLX:
- Mac model:

**Comment by adefossez** [comment]
I'm pretty sure ChatGPT could help you debug this one.
Seems like you don't have the permissions to edit your own .bash_profile, which is quite strange.
if you do 
```bash
ls -lht ~/.bash*
```

what does it show ?

**Comment by haqatak** [comment]
have tried to use python 3.12?

**Comment by louis030195** [comment]
can it even run on mac? i tried to run the rust server and my macbook pro m3 32 gb ram had an heart attack (died)

**Comment by LaurentMazare** [comment]
It should run, the best bet is the MLX quantized version which I've tested on a M3 air 16G, M2 pro 16G, and M3 max 36G without issues.

**Comment by adefossez** [comment]
As the original author didn't reply in a while, I'll be closing this issue
