### ISSUE TITLE
Plans for Integrating Moshi with Native Huggingface

### ISSUE THREAD

**Issue by patrick-tssn** [kyutai-labs/moshi#67]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The PyTorch implementation

### Question

Thank you for your impressive work. Do you have any plans to integrate Moshi with the native Huggingface?

**Comment by julien-c** [comment]
What do you mean exactly @patrick-tssn?

**Comment by patrick-tssn** [comment]
I mean incorporate Moshi into Huggingface models like Mimi:
`from transformers import MimiModel, AutoFeatureExtractor`

**Comment by adefossez** [comment]
The amazing team at Hugging Face is working on the integration right now. Might take a few days to land :)
