### ISSUE TITLE
Finetune code

### ISSUE THREAD

**Issue by tonychenxyz** [kyutai-labs/moshi#74]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

Other / All

### Question

Is code to finetune moshi available?

**Comment by akshatvishu** [comment]
They said that training/fine-tune code will be released somewhere in the near future but didn't put an exact date on it.

ref: <https://github.com/kyutai-labs/moshi/blob/main/FAQ.md>

**Comment by matbee-eth** [comment]
"Please be patient"

This is a skill I do not possess
