### ISSUE TITLE
Custom prompt

### ISSUE THREAD

**Issue by haqatak** [kyutai-labs/moshi#76]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The MLX implementation

### Question

Is there a way to set a custom prompt, to make the LLM focus on a particular topic?

**Comment by tomasmcm** [comment]
similar to this, how would one build a RAG system with this? 
We would need access to what the user is talking about and a way to append data related to that for the model to use in the response.

**Comment by amine7777** [comment]
I think this will be a game changer !

**Comment by hp2413** [comment]
As per the FAQs, I think at the moment it is not supported

Can I change Moshi's voice / personality?
This would require fine tuning, which is not currently supported.

**Comment by haqatak** [comment]
prompt engineering is not the same as fine tuning :)

**Comment by ajayjakkampudi** [comment]
How can I use custom prompts in this code to ensure that the chatbot follows specific instructions?

**Comment by adefossez** [comment]
There is no support at the moment to do that, as mentioned in the FAQ!
