### ISSUE TITLE
Mimi - Encoder/decoder

### ISSUE THREAD

**Issue by matbee-eth** [kyutai-labs/moshi#77]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The paper

### Question

Can a stream of Mimi encoded audio be directly decoded to WAV? As in, if I stream the encoded mimi tokens, by decoding the tokens, will I have usable audio? Or- is it coupled to Moshika/ko to produce decodable (low-bitrate) audio?

**Comment by LaurentMazare** [comment]
Yes a stream of mimi tokens can be directly decoded to wav. In this [example](https://github.com/kyutai-labs/moshi/blob/main/scripts/mimi_streaming_test.py) you can see some audio file being loaded, then converted to mimi audio tokens, then back to a wav file, all this being done in a streaming way.

**Comment by adefossez** [comment]
See also this [README](https://github.com/kyutai-labs/moshi/tree/main/moshi#api).
