### ISSUE TITLE
Interruption

### ISSUE THREAD

**Issue by SinanAkkoyun** [kyutai-labs/moshi#79]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

Other / All

### Question

Hello, thank you very much for the great work! How did you achieve non-interrupting behaviour?

**Comment by akshatvishu** [comment]
I think they touch on this at  Section 3.4.4 Inner Monologue  in the [paper](<https://kyutai.org/Moshi.pdf>)

**Comment by SinanAkkoyun** [comment]
> Interestingly, there is no explicit boundaries for the change of turns between
the user and Moshi: Moshi can speak and listen at all time, and do both at once if needed

They indeed do, thank you!
