### ISSUE TITLE
Programming access to moshi-mlx

### ISSUE THREAD

**Issue by atanudasgupta** [kyutai-labs/moshi#80]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The MLX implementation

### Question

Is there a programmatic access to moshi-mlx , which I can use with python? if yes, please provide any example.

**Comment by LaurentMazare** [comment]
There is a programmatic access to moshi-mlx, you can see it being used in this [script](https://github.com/kyutai-labs/moshi/blob/3df7e806af2f90b75ef5d12b6c5126113cc065ff/scripts/test_mlx.py#L85), `run_audio_gen_stream` is the function that takes as input a moshi model, and a mimi checkpoint and runs both of them together, the script should also show you how this gets initialized.
