### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by yukiarimo** [kyutai-labs/moshi#81]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

Other / All

### Question

Hello! It looks like an incredible mode! I have a few questions about it:

1. What’s the base architecture/model?
2. How can I fine-tune it both using text-only and text-to-speech and speech-to-speech (like on a custom voice) in google colab?
3. Tokenizer type? How can I add some new tokens?
4. Is it STT, too?
5. Can it recognize images?
6. It is supported somewhere else, like llama cpp?

**Comment by LaurentMazare** [comment]
1. See the [paper](https://arxiv.org/abs/2410.00037) for details on the architecture.
2. We don't provide support for fine-tuning yet, though we plan on having some at some point, see the [FAQ](https://github.com/kyutai-labs/moshi/blob/main/FAQ.md).
3. Text tokenizer is sentencepiece, not sure how one would add tokens there.
4. Moshi is the conversational agent so only does speech to speech. The fundation model and overall process can be used for STT though as mentioned in the paper.
5. No support for vision at the moment.
6. Not sure, you will probably have to search for this.
