### ISSUE TITLE
0.0.0.0:8998 web ui can‘t clink connect

### ISSUE THREAD

**Issue by dcmouth** [kyutai-labs/moshi#86]
### Backend impacted

The PyTorch implementation

### Operating system

Linux

### Hardware

GPU

### Description

when i run python -m moshi.server   then 
![WX20240920-162156@2x](https://github.com/user-attachments/assets/e661336d-2e07-42ce-820f-712b0e75e375)
but i can click settings but i can't click connect 

### Extra information

none

### Environment

Fill in the following information on your system.
- Operating system version:

If the backend impacted is PyTorch:
- Python version: 3.11
- PyTorch version: 2.2.0 
- CUDA version (run `python -c 'import torch;  print(torch.version.cuda)'`):  12.1 
- GPU model and memory: 24
  
ubuntu

**Comment by LaurentMazare** [comment]
Pretty tricky to tell what is going on here:
- It could be an issue on the frontend. What browser are you using? (we would recommend chrome as we mostly tested the UI with it) anything interesting in the javascript console?
- It could be that the backend crashed, anything you can find in the logs printed by the `python` command that would be of interest?

**Comment by hugh-min** [comment]
Exactly same problem here on a ubuntu server. After clicking "Connect" the browser will return following message in the browser's console:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addModule')
    at index-ClFQVzk0.js:431:71092
    at index-ClFQVzk0.js:431:71260
    at onClick (index-ClFQVzk0.js:431:73819)
    at Object.Nb (index-ClFQVzk0.js:37:9852)
    at Tb (index-ClFQVzk0.js:37:10006)
    at Ub (index-ClFQVzk0.js:37:10063)
    at nf (index-ClFQVzk0.js:37:31422)
    at se (index-ClFQVzk0.js:37:31839)
    at index-ClFQVzk0.js:37:36991
    at Qk (index-ClFQVzk0.js:40:36798)

**Comment by LaurentMazare** [comment]
In this last case, I would guess the issue is on [this line](https://github.com/kyutai-labs/moshi/blob/ae34219a1bd0e7d107254efdc6a5b45b4950fa42/client/src/pages/Queue/Queue.tsx#L59) where `audioContext.audioWorlket` is undefined. This seems quite surprising as this has been available in chrome for a long time (chrome 66 in 2018) so not sure what is going on here. You can try this [page](https://googlechromelabs.github.io/web-audio-samples/audio-worklet/basic/hello-audio-worklet/) to see if audio worklets work properly in your browser, but besides that I don't have much ideas to offer.

**Comment by KaruroChori** [comment]
go to localhost:8998. I hafd the same issue.

**Comment by Alex-Songs** [comment]
I had the same issue. are you solved? @KaruroChori

**Comment by hugh-min** [comment]
I use a Chrome browser with verion 129.0.6668 and assess.Could not try localhost:8998 because I use a remote server.

**Comment by AWAS666** [comment]
After a bit of research, it appears to be a https issue, audioWorklet is only available in a https context:
[see here](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/audioWorklet)

**Comment by LaurentMazare** [comment]
I don't think the https restriction applies to localhost actually.

**Comment by AWAS666** [comment]
> I don't think the https restriction applies to localhost actually.

this only happens if not run on localhost, so for example providing "--host 0.0.0.0"

**Comment by Alex-Songs** [comment]
@AWAS666 Hi，are you solved?

**Comment by Alex-Songs** [comment]
@hugh-min Hi, I also use remote server, are you sloved?

**Comment by hugh-min** [comment]
> After a bit of research, it appears to be a https issue, audioWorklet is only available in a https context: [see here](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/audioWorklet)

confirmed that's the issue

**Comment by LaurentMazare** [comment]
In that case, you should just tunnel the remote port through ssh so that you can actually use http://localhost:8998 (details in the readme).

**Comment by dcmouth** [comment]
> > After a bit of research, it appears to be a https issue, audioWorklet is only available in a https context: [see here](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/audioWorklet)经过一番研究，它似乎是一个https问题，audioWorklet只在https上下文中可用：[请参阅此处](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/audioWorklet)
> 
> confirmed that's the issue证实这就是问题所在

so what can i do to solve the problem ?

**Comment by jianglan89** [comment]
> > > After a bit of research, it appears to be a https issue, audioWorklet is only available in a https context: [see here](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/audioWorklet)经过一番研究，它似乎是一个https问题，audioWorklet只在https上下文中可用：[请参阅此处](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/audioWorklet)
> > 
> > 
> > confirmed that's the issue证实这就是问题所在
> 
> so what can i do to solve the problem ?
gen your CERT_FILE and KEY_FILE
use cmd: openssl req -x509 -newkey rsa:4096 -nodes -out cert.pem -keyout key.pem -days 365

update your iptables
  iptables -A INPUT -p tcp --dport 8998 -j ACCEPT
  service iptables restart

update server.py

    CERT_FILE = f'{HOME}/.ssh/cert.pem'
    KEY_FILE = f'{HOME}/.ssh/key.pem'

    import ssl
    ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
    ssl_context.load_cert_chain(certfile=CERT_FILE, keyfile=KEY_FILE)
    web.run_app(app, port=args.port, ssl_context=ssl_context)

**Comment by dcmouth** [comment]
> > > > After a bit of research, it appears to be a https issue, audioWorklet is only available in a https context: [see here](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/audioWorklet)经过一番研究，它似乎是一个https问题，audioWorklet只在https上下文中可用：[请参阅此处](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/audioWorklet)
> > > 
> > > 
> > > confirmed that's the issue证实这就是问题所在
> > 
> > 
> > so what can i do to solve the problem ?
> 
> 1. gen your CERT_FILE and KEY_FILE
>    use cmd: openssl req -x509 -newkey rsa:4096 -nodes -out cert.pem -keyout key.pem -days 365
> 2. update your iptables
>    iptables -A INPUT -p tcp --dport 8998 -j ACCEPT
>    service iptables restart
> 3. update server.py and restart server
>    CERT_FILE = f'{HOME}/.ssh/cert.pem'
>    KEY_FILE = f'{HOME}/.ssh/key.pem'
>    import ssl
>    ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
>    ssl_context.load_cert_chain(certfile=CERT_FILE, keyfile=KEY_FILE)
>    web.run_app(app, port=args.port, ssl_context=ssl_context)
> 4. use https://x.x.x.x:8998/

thats great,thx. I solve my problem . according to you notice  that is my step below .

（1） openssl req -x509 -newkey rsa:4096 -nodes -out cert.pem -keyout key.pem -days 365   
（2）sudo update-alternatives --config iptables  
 and chose iptables-legacy 
（3）sudo iptables -A INPUT -p tcp --dport 8998 -j ACCEPT   
(4) service iptables restart     
(5) In moshi/server.py add
HOME = os.path.expanduser("~")
CERT_FILE = f'{HOME}/cert.pem'
KEY_FILE = f'{HOME}/key.pem' 
import ssl
ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
ssl_context.load_cert_chain(certfile=CERT_FILE, keyfile=KEY_FILE) 
web.run_app(app, port=args.port,  ssl_context=ssl_context)

then  restart server 
(6)use https://x.x.x.x:8998/

**Comment by LaurentMazare** [comment]
Just to mention that there is now a `--ssl` argument for both the pytorch and mlx version so that serving is done over https rather than http. You have to pass to this argument a directory that contains the key and certificate files.
