### ISSUE TITLE
Inference settings for Spoken QA benchmark

### ISSUE THREAD

**Issue by sphmel** [kyutai-labs/moshi#87]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The paper

### Question

I want to perform Spoken Question Answering as in paper section 5.5

But I'm not sure which setting is proper. Moshi always generate their greetings first like "Hello, How are you today?". 

Is it okay to input spoken question at first, which will overlap greeting? also how to detect moshi's answer finished? should i check text pad token?

**Comment by LaurentMazare** [comment]
If I remember correctly the spoken QA setup was not using the conversational moshi model (i.e. the ones with the greetings) but rather the base model that was later fine tuned to be conversational. So at the moment, there is no easy way to run this benchmark in the same setting, you could try just waiting for the greetings to end (either wait for ~5s or use some vad) and ask the question. Would be interesting to know the result if you end up doing so.
