### ISSUE TITLE
Text Token is always 3

### ISSUE THREAD

**Issue by Alex-Songs** [kyutai-labs/moshi#98]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The PyTorch implementation

### Question

I started a web app, but the chat window does not have any output. The server-side text_token is constantly 3:
<img width="1073" alt="image" src="https://github.com/user-attachments/assets/440b2580-8e7c-485b-a34f-c27845719550">

**Comment by unfailingsalvage1448** [comment]
Why did you close it? What was the answer?
